name: build_and_test
on: 
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  lint-and-format: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.18'
      - name: install
        run: npm install
      - name: check format
        run: npm run format:check
      - name: lint
        run: npm run lint

  build: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.18'
      - name: install
        run: npm install
      - name: build
        run: npm run build
