name: build_and_test
on: 
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  lint-and-format: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.18'
      - name: install
        run: npm install
      - name: check format
        run: npm run format:check
      - name: lint
        run: npm run lint

  build: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.18'
      - name: install
        run: npm install
      - name: build
        run: npm run build

  deployPRDraft:
    name: Deploy draft to Netlify
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.ref != 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.18'
      - name: install
        run: npm install
      - name: build
        env:
          REACT_APP_IMAGEKIT_PUBLIC_KEY: ${{ secrets.REACT_APP_IMAGEKIT_PUBLIC_KEY }}
          REACT_APP_IMAGEKIT_URL_ENDPOINT: ${{ secrets.REACT_APP_IMAGEKIT_URL_ENDPOINT }}
          REACT_APP_REST_API_BASE_URL: ${{ secrets.REACT_APP_REST_API_BASE_URL }}
        run: npm run build

      - name: Deploy draft to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './build'
          draft: true
          comment-on-pull-request: true
