name: CD

on:
  push:
    branches: [main]

jobs:
  publishMasterCommit:
    name: Publish to Netlify
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.18'
      - name: install
        run: npm install
      - name: build
        env:
          REACT_APP_IMAGEKIT_PUBLIC_KEY: ${{ secrets.REACT_APP_IMAGEKIT_PUBLIC_KEY }}
          REACT_APP_IMAGEKIT_URL_ENDPOINT: ${{ secrets.REACT_APP_IMAGEKIT_URL_ENDPOINT }}
        run: npm run build

      - name: Deploy production to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './build'
          comment-on-commit: true
